### ISSUE TITLE
Modelado de DB. DER, Modelo Relacional.

### ISSUE THREAD

**Issue by abrilramos12** [abrilramos12/Proyecto_Grupal-Ispc#5]

**Comment by jnramos24** [comment]
Creo modelos de entidad relación de acuerdo a lo estipulado. Cierro tarea.

**Comment by jnramos24** [comment]
Pd: Abril aceptame el pull request de la rama develop así pusheo los cambios.

**Comment by jnramos24** [comment]
Reabierta por error se cierra.
